Repository ice-lab/iceworks, pull requests merged in 2020-06, with the labels that each got.

#42 Feat/theme
  extensions/iceworks-component-builder/build.json
  extensions/iceworks-component-builder/package.json
  extensions/iceworks-component-builder/src/global.scss
  extensions/iceworks-component-builder/src/pages/Home/index.module.scss
  extensions/iceworks-component-builder/src/pages/Home/index.tsx
  extensions/iceworks-page-builder/build.json
  extensions/iceworks-page-builder/package.json
  extensions/iceworks-page-builder/src/global.scss
  extensions/iceworks-page-builder/src/pages/Home/index.module.scss
  extensions/iceworks-page-builder/src/pages/Home/index.tsx
  extensions/iceworks-project-creator/build.json
  extensions/iceworks-project-creator/mocks/material/getSources.json
  extensions/iceworks-project-creator/mocks/project/getScaffolds.json
  extensions/iceworks-project-creator/package.json
  extensions/iceworks-project-creator/src/callService.ts
  extensions/iceworks-project-creator/src/components/SelectCard/index.module.scss
  extensions/iceworks-project-creator/src/global.scss
  extensions/iceworks-project-creator/src/pages/CreateProject/components/Header/index.module.scss
  extensions/iceworks-project-creator/src/pages/CreateProject/components/Header/index.tsx
  extensions/iceworks-project-creator/src/pages/CreateProject/components/ScaffoldMarket/index.tsx
  extensions/iceworks-project-creator/src/pages/CreateProject/index.module.scss
  extensions/iceworks-project-creator/src/pages/CreateProject/index.tsx
  packages/material-ui/build.json
Labels: enhancement

#71 Fix: fix create component&page entry icon not found
  extensions/iceworks-app/package.json
  extensions/iceworks-app/package.nls.json
  extensions/iceworks-app/package.nls.zh-cn.json
  extensions/iceworks-app/src/extension.ts
Labels: bug

#127 docs: fix image link
  README.en.md
  README.md
  extensions/iceworks-material-helper/README.md
  extensions/iceworks-material-helper/package.json
Labels: iceworks-vscode
